name: chat_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter




  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  google_sign_in: ^6.0.2
  profanity_filter: ^2.0.0

dev_dependencies:
  dependency_validator: ^3.0.0

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


